### ISSUE TITLE
PR Comment dont work

### ISSUE THREAD

**Issue by steinbrueckri** [burdzwastaken/hadolint-action#13]
Hi,
first of all many thanks for this great Github action, sadly the PR Comment doesn't work.
When I find time next week, I'll try to fix the problem myself. If I can manage it, I will do a PR for it.

PR: https://github.com/steinbrueckri/envsubst/pull/1
Issue: https://github.com/burdzwastaken/hadolint-action/blob/bc294712bbcee46ff0e3dbbe52c6ccf772dc3e4b/hadolint-action.sh#L35

**Comment by burdzwastaken** [comment]
Hi @steinbrueckri, 

I am so sorry I missed this pull request until now. Thanks for the issue, please let me know if you want to work on the fix or I can over the next few days.

Thanks!

**Comment by burdzwastaken** [comment]
@steinbrueckri I just ran the actions on a `test/` branch [here](https://github.com/burdzwastaken/hadolint-action/pull/15). From my observation I can see the PR comments. Please let me know how I can reproduce this error.

**Comment by steinbrueckri** [comment]
@burdzwastaken it works 👍 ... not sure why it didn't in the first try.
