### ISSUE TITLE
Mention Inline-Ignores to pass own rules and exceptions

### ISSUE THREAD

**Issue by wernerfred** [burdzwastaken/hadolint-action#20]
Thanks for that nice little action!

At the [ToDo](https://github.com/burdzwastaken/hadolint-action#todo) section you say:

- Let users supply their own hadolint.yaml and/or trusted registries passed through

As i needed such a functionality right now i looked at the linked hadolink repository and found the possitbility of [Inline-Ignores](https://github.com/hadolint/hadolint#inline-ignores)

Maybe it is possible to add that hint to your actions readme so that people can use this method in the meantime (needs to be validated for sure, haven't tested it right now)

Cheers

**Comment by burdzwastaken** [comment]
I will totally add that to the documentation. thanks for the idea.
