### ISSUE TITLE
Trigger action on PR commit only

### ISSUE THREAD

**Issue by CCFenner** [burdzwastaken/hadolint-action#7]
Hi there, thanks for this GH action!

But I have an issue, it seems that the action is also triggered if I change the PR (adding reviewers). Any idea how to limit this to PR commits only?

![Bildschirmfoto 2019-04-10 um 11 14 33](https://user-images.githubusercontent.com/26137398/55868080-0b9a8f00-5b84-11e9-899a-f64a0a4e9b86.png)

**Comment by burdzwastaken** [comment]
@CCFenner thanks for reporting this! let me take a look into ways to limit it to only when commits are made. (sorry for the late response)

**Comment by burdzwastaken** [comment]
it seems this is a limitation of the `pull_request` event. 

"Triggered when a pull request is assigned, unassigned, labeled, unlabeled, opened, edited, closed, reopened, synchronize, ready_for_review, locked, unlocked, a pull request review is requested, or a review request is removed."

ref: https://developer.github.com/actions/managing-workflows/workflow-configuration-options/#events-supported-in-workflow-files

I should be able to inspect the payload to make sure this is only ran when the event is: `opened, edited and synchronize`.

**Comment by burdzwastaken** [comment]
This is now handled in the github action syntax: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onevent_nametypes
